name = "MQLib"
uuid = "16f11440-1623-44c9-850c-358a6c72f3c9"
authors = ["pedromxavier <pedroxavier@psr-inc.com>", "pedroripper <pedroripper@psr-inc.com>"]
version = "0.3.0"

[deps]
MQLib_jll = "4dedf8fe-8d9a-5fb8-8563-19379e8d5c54"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
QUBODrivers = "a3f166f7-2cd3-47b6-9e1e-6fbfe0449eb0"
QUBOTools = "60eb5b62-0a39-4ddc-84c5-97d2adff9319"

[compat]
MQLib_jll = "0.1"
Printf = "1"
QUBODrivers = "0.3"
QUBOTools = "0.9"
julia = "1.9"
