name    = "MQLib"
uuid    = "16f11440-1623-44c9-850c-358a6c72f3c9"
authors = [
    "pedromxavier <pedroxavier@psr-inc.com>",
    "pedroripper <pedroripper@psr-inc.com>",
]
version = "0.1.2"

[deps]
Anneal    = "e4d9eb7f-b088-426e-aeb5-1c0dae3d8abb"
MQLib_jll = "4dedf8fe-8d9a-5fb8-8563-19379e8d5c54"
Printf    = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
Anneal    = "0.6"
MQLib_jll = "0.1"
julia     = "1.6"
